#%RAML 1.0 DataType
displayName: API-Inventory-DataType
description: Defines the fields in API-Inventory Datatype

type: object
properties:
  environment?: string
  country?: string
  project?: string
  TMF?: string
  API?: string
  url?: string
  description?: string
  layer?: string