#%RAML 1.0 NamedExample

value:
-
  API: "ecom-ux"
  url: "http://localhost:8080/ecom-ux/v1/console/"
  description: "Experience"
  country: "Jamaica"
  project: "self-install"
  TMF: "tmf629"
-
  API: "liberate-customer-sys"
  url: "http://localhost:9092/liberate-customer-sys/v1/console/"
  description: "System"
  country: "Jamaica"
  project: "self-install"
  TMF: "tmf666"